### ISSUE TITLE
API Design Changes

### ISSUE THREAD

**Issue by Bustinout** [Bustinout/CS591-MAD-Don-t-Be-Chicken#2]
Need to do:

API Call to remove self from queue.
Change "currentMeetingId" to String in 3rd party login call
Separate calls for UpdateName and UpdateImage (It makes it so I can do both separately without having to save either locally)

Add to user model
"eventsAttended": int
"accountsMet": array of userIDs met

in LeaveGroup call, it should increment eventsAttended by 1 and add all userIDs of group members to accountsMet (if not already in the array)

Question:
For the image upload, should I send a bitmap?

**Comment by samzhu333** [comment]
- API Call to remove self from queue.
Done

- Change "currentMeetingId" to String in 3rd party login call
All meeting Ids are long, it shouldn't be changed to a String.

- Separate calls for UpdateName and UpdateImage
It is not a good try. User profiles should be saved locally to reduce server burden. Also, changes of user profile should use only one function to simplify both front end and back end code.

- Add to user model
Done

- in LeaveGroup call, it should increment eventsAttended by 1 and add all userIDs of group members to accountsMet
Done

- For the image upload, should I send a bitmap?
For simplify, let's first restrict all image to be .jpg files.

**Comment by Bustinout** [comment]
Thanks.

I've changed currentMeetingID to long. Can you tell me what will be returned if the user is not currently in a meeting?



Extra stuff to add
